openapi: 3.0.0
info:
  title: Payment API
  description: API responsável pelo processamento de pagamentos dentro do sistema.
  version: v1
servers:
- url: https://virtserver.swaggerhub.com/dinedash/paymentAPI/v1
  description: Mock Server (SwaggerHub)
paths:
  /v1/payments:
    get:
      summary: Filtrar pagamentos
      description: "Obtém uma lista de pagamentos filtrados por status, método e paginação."
      operationId: getFilteredPayments
      parameters:
      - name: status
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: approved
          enum:
          - approved
          - rejected
          - pending
      - name: method
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: credit_card
          enum:
          - credit_card
          - paypal
          - bank_transfer
      - name: limit
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
          example: 10
      - name: offset
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
          example: 0
      responses:
        "200":
          description: Lista de pagamentos filtrados.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentResponse'
        "400":
          description: Parâmetros inválidos.
        "500":
          description: Erro interno do servidor.
    put:
      summary: Atualizar status do pagamento
      description: Atualiza o status de um pagamento existente.
      operationId: updatePaymentStatus
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentStatusUpdate'
        required: true
      responses:
        "200":
          description: Status do pagamento atualizado com sucesso.
        "400":
          description: Requisição inválida.
        "404":
          description: Pagamento não encontrado.
        "500":
          description: Erro interno do servidor.
    post:
      summary: Criar um novo pagamento
      description: Registra um novo pagamento no sistema.
      operationId: createPayment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
        required: true
      responses:
        "201":
          description: Pagamento criado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        "400":
          description: Requisição inválida.
        "500":
          description: Erro interno do servidor.
  /v1/payments/{payment_id}:
    get:
      summary: Obter status do pagamento
      description: Retorna o status de um pagamento específico.
      operationId: getPaymentStatus
      parameters:
      - name: payment_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Status do pagamento retornado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        "404":
          description: Pagamento não encontrado.
        "500":
          description: Erro interno do servidor.
    delete:
      summary: Deletar um pagamento
      description: Remove um pagamento específico do sistema.
      operationId: deletePayment
      parameters:
      - name: payment_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Pagamento removido com sucesso.
        "404":
          description: Pagamento não encontrado.
        "500":
          description: Erro interno do servidor.
components:
  schemas:
    PaymentRequest:
      type: object
      properties:
        order_id:
          type: string
          example: "123456"
        amount:
          type: number
          format: float
          example: 50
        method:
          type: string
          example: credit_card
          enum:
          - credit_card
          - paypal
          - bank_transfer
    PaymentResponse:
      type: object
      properties:
        payment_id:
          type: string
          example: abc123
        status:
          type: string
          example: pending
          enum:
          - approved
          - rejected
          - pending
        amount:
          type: number
          format: float
          example: 50
        method:
          type: string
          example: credit_card
    PaymentStatusUpdate:
      type: object
      properties:
        payment_id:
          type: string
          example: abc123
        status:
          type: string
          example: approved
          enum:
          - approved
          - rejected
          - pending
