# filepath: [docker-compose.yml](http://_vscodecontentref_/0)
services:
  api:
    build: .
    ports:
      - "8003:8003"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: