services:
  api:
    build: .
    ports:
      - "8003:8003"
    environment:
      - MONGO_URI=mongodb://payment-mongo:27017
    depends_on:
      - payment-mongo

  payment-mongo:
    image: mongo:6
    container_name: "payment-mongo"
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
