# generated by datamodel-codegen:
#   filename:  dinedash-paymentAPI-v1-resolved.yaml
#   timestamp: 2025-03-11T16:03:46+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Method(Enum):
    credit_card = 'credit_card'
    paypal = 'paypal'
    bank_transfer = 'bank_transfer'


class PaymentRequest(BaseModel):
    order_id: Optional[str] = Field(None, example='123456')
    amount: Optional[float] = Field(None, example=50)
    method: Optional[Method] = Field(None, example='credit_card')


class Status(Enum):
    approved = 'approved'
    rejected = 'rejected'
    pending = 'pending'


class PaymentResponse(BaseModel):
    payment_id: Optional[str] = Field(None, example='abc123')
    status: Optional[Status] = Field(None, example='pending')
    amount: Optional[float] = Field(None, example=50)
    method: Optional[str] = Field(None, example='credit_card')


class PaymentStatusUpdate(BaseModel):
    payment_id: Optional[str] = Field(None, example='abc123')
    status: Optional[Status] = Field(None, example='approved')
